/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu7_Opciones.java
 *
 * Created on 28-may-2011, 14:01:45
 */

package EXE.Interface;

/**
 *
 * @author jose.manuel.ramos
 */
public class Menu7_Opciones extends javax.swing.JFrame {

    /** Creates new form Menu7_Opciones */
    public Menu7_Opciones() {
        initComponents();
    }

     private int accion = 0;

     public int get_accion() {
        int aux = accion;
        accion = 0;
        return aux;
     }

     public int getn (){
         String p = TextN.getText();
         if(p.length() == 1) return java.lang.Integer.parseInt(p);
         return -1;
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        color = new javax.swing.JButton();
        cargasdefault = new javax.swing.JButton();
        changen = new javax.swing.JButton();
        manual = new javax.swing.JButton();
        back = new javax.swing.JButton();
        TextN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        color.setText("Color resaltado");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        cargasdefault.setText("Cambiar cargas por defecto");
        cargasdefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargasdefaultActionPerformed(evt);
            }
        });

        changen.setText("Cambiar N");
        changen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changenActionPerformed(evt);
            }
        });

        manual.setText("Manual d' usuari");
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        back.setText("Atras");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        TextN.setText("Introducir N");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextN, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(manual, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(cargasdefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(color)
                .addGap(18, 18, 18)
                .addComponent(cargasdefault)
                .addGap(18, 18, 18)
                .addComponent(manual)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changen)
                    .addComponent(TextN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changenActionPerformed
        // TODO add your handling code here:
        accion = 1;
}//GEN-LAST:event_changenActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
        accion = 2;
    }//GEN-LAST:event_colorActionPerformed

    private void cargasdefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargasdefaultActionPerformed
        // TODO add your handling code here:
        accion = 3;
    }//GEN-LAST:event_cargasdefaultActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        // TODO add your handling code here:
        accion = 4;
}//GEN-LAST:event_manualActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        accion = 6;
}//GEN-LAST:event_backActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextN;
    private javax.swing.JButton back;
    private javax.swing.JButton cargasdefault;
    private javax.swing.JButton changen;
    private javax.swing.JButton color;
    private javax.swing.JButton manual;
    // End of variables declaration//GEN-END:variables

}
